\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{resume}[2019/04/29 Resume LaTeX Class]

% SECTION: HEADER
%   \name
%   \address
%   \phonenumber
%   \email
%   \linkedin
%   \github

% SECTION: OBJECTIVE
%   \objective

% SECTION: KEY STRENGTHS
%   \strength

% SECTION: EXPERIENCE
%   \employer
%   \location
%   \datestart
%   \dateend
%   \jobtitle
%   \duration -> can this be auto-calculated?
%   \accomplishment

% SECTION: EDUCATION
%   \institution
%   \location
%   \datestart
%   \dateend
%   \degree
%   \conferred
%   \accomplishment
